/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Int,
  'type' : IDL.Text,
  'comment' : IDL.Text,
  'assetSymbol' : IDL.Text,
  'assetName' : IDL.Text,
  'price' : IDL.Float64,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const UserProfile = IDL.Record({
  'theme' : IDL.Text,
  'name' : IDL.Text,
  'language' : IDL.Text,
  'colorScheme' : IDL.Text,
});
export const AuthResult_1 = IDL.Variant({
  'ok' : UserProfile,
  'notFound' : IDL.Text,
  'unauthorized' : IDL.Text,
});
export const MarketData = IDL.Record({
  'id' : IDL.Nat,
  'marketCap' : IDL.Float64,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const MarketDataStatus = IDL.Record({
  'status' : IDL.Text,
  'calculationQuality' : IDL.Float64,
  'apiHealth' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'trackedAssetsCount' : IDL.Nat,
  'colorScheme' : IDL.Text,
});
export const Asset = IDL.Record({
  'currentPrice' : IDL.Float64,
  'averagePrice' : IDL.Float64,
  'realizedProfitLossPercentage' : IDL.Float64,
  'name' : IDL.Text,
  'averagePurchasePrice' : IDL.Float64,
  'profitLoss' : IDL.Float64,
  'currentValue' : IDL.Float64,
  'purchaseValue' : IDL.Float64,
  'profitLossPercentage' : IDL.Float64,
  'amount' : IDL.Float64,
  'totalSoldCost' : IDL.Float64,
  'realizedProfitLoss' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const Portfolio = IDL.Record({
  'id' : IDL.Nat,
  'totalProfitLoss' : IDL.Float64,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'assets' : IDL.Vec(Asset),
  'trackedAssets' : IDL.Vec(IDL.Text),
  'totalPurchaseValue' : IDL.Float64,
  'transactions' : IDL.Vec(Transaction),
  'unrealizedProfitLoss' : IDL.Float64,
});
export const AuthResult = IDL.Variant({
  'ok' : IDL.Vec(Portfolio),
  'notFound' : IDL.Text,
  'unauthorized' : IDL.Text,
});
export const PriorityAsset = IDL.Record({
  'id' : IDL.Text,
  'marketCap' : IDL.Float64,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const TechnicalData = IDL.Record({
  'currentPrice' : IDL.Float64,
  'change24h' : IDL.Float64,
  'marketCap' : IDL.Float64,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'volume24h' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addCustomPriorityAsset' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Record({ 'error' : IDL.Opt(IDL.Text), 'success' : IDL.Bool })],
      [],
    ),
  'addTransaction' : IDL.Func([IDL.Nat, Transaction], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPortfolio' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deletePortfolio' : IDL.Func([IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'editTransaction' : IDL.Func([IDL.Nat, IDL.Nat, Transaction], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'fetchHistoricalPriceData' : IDL.Func([IDL.Text], [IDL.Text], []),
  'fetchMarketData' : IDL.Func([], [], []),
  'fetchPriorityAssetPrices' : IDL.Func([], [], []),
  'fetchTechnicalData' : IDL.Func([IDL.Text], [], []),
  'getAvailableAssets' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserProfileWithStatus' : IDL.Func([], [AuthResult_1], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomPriorityAssets' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getHistoricalPrice' : IDL.Func([IDL.Text, IDL.Int], [IDL.Float64], []),
  'getLastFetchError' : IDL.Func(
      [],
      [
        IDL.Record({
          'marketData' : IDL.Opt(
            IDL.Record({ 'error' : IDL.Text, 'timestamp' : IDL.Int })
          ),
          'priorityAssets' : IDL.Opt(
            IDL.Record({ 'error' : IDL.Text, 'timestamp' : IDL.Int })
          ),
          'technicalData' : IDL.Opt(
            IDL.Record({ 'error' : IDL.Text, 'timestamp' : IDL.Int })
          ),
        }),
      ],
      ['query'],
    ),
  'getMarketData' : IDL.Func([], [IDL.Vec(MarketData)], ['query']),
  'getMarketDataStatus' : IDL.Func([], [IDL.Opt(MarketDataStatus)], ['query']),
  'getPortfolioAssets' : IDL.Func([IDL.Nat], [IDL.Vec(Asset)], ['query']),
  'getPortfolioSummary' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Opt(
          IDL.Record({
            'totalProfitLoss' : IDL.Float64,
            'totalValue' : IDL.Float64,
            'totalPurchaseValue' : IDL.Float64,
            'unrealizedProfitLoss' : IDL.Float64,
          })
        ),
      ],
      ['query'],
    ),
  'getPortfolioTrackedAssets' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getPortfolioTransactions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getPortfolios' : IDL.Func([], [IDL.Vec(Portfolio)], ['query']),
  'getPortfoliosWithStatus' : IDL.Func([], [AuthResult], ['query']),
  'getPriorityAssets' : IDL.Func([], [IDL.Vec(PriorityAsset)], ['query']),
  'getSystemHealth' : IDL.Func(
      [],
      [
        IDL.Record({
          'isHealthy' : IDL.Bool,
          'currentTime' : IDL.Int,
          'lastCheck' : IDL.Int,
        }),
      ],
      ['query'],
    ),
  'getTechnicalData' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TechnicalData)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isAuthenticated' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeCustomPriorityAsset' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'error' : IDL.Opt(IDL.Text), 'success' : IDL.Bool })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchCoinGeckoTokens' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'results' : IDL.Vec(
            IDL.Record({
              'id' : IDL.Text,
              'name' : IDL.Text,
              'symbol' : IDL.Text,
            })
          ),
          'error' : IDL.Opt(IDL.Text),
        }),
      ],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAssetPrices' : IDL.Func([IDL.Nat], [], []),
  'updateMarketDataStatus' : IDL.Func([MarketDataStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Int,
    'type' : IDL.Text,
    'comment' : IDL.Text,
    'assetSymbol' : IDL.Text,
    'assetName' : IDL.Text,
    'price' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const UserProfile = IDL.Record({
    'theme' : IDL.Text,
    'name' : IDL.Text,
    'language' : IDL.Text,
    'colorScheme' : IDL.Text,
  });
  const AuthResult_1 = IDL.Variant({
    'ok' : UserProfile,
    'notFound' : IDL.Text,
    'unauthorized' : IDL.Text,
  });
  const MarketData = IDL.Record({
    'id' : IDL.Nat,
    'marketCap' : IDL.Float64,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const MarketDataStatus = IDL.Record({
    'status' : IDL.Text,
    'calculationQuality' : IDL.Float64,
    'apiHealth' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'trackedAssetsCount' : IDL.Nat,
    'colorScheme' : IDL.Text,
  });
  const Asset = IDL.Record({
    'currentPrice' : IDL.Float64,
    'averagePrice' : IDL.Float64,
    'realizedProfitLossPercentage' : IDL.Float64,
    'name' : IDL.Text,
    'averagePurchasePrice' : IDL.Float64,
    'profitLoss' : IDL.Float64,
    'currentValue' : IDL.Float64,
    'purchaseValue' : IDL.Float64,
    'profitLossPercentage' : IDL.Float64,
    'amount' : IDL.Float64,
    'totalSoldCost' : IDL.Float64,
    'realizedProfitLoss' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const Portfolio = IDL.Record({
    'id' : IDL.Nat,
    'totalProfitLoss' : IDL.Float64,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'assets' : IDL.Vec(Asset),
    'trackedAssets' : IDL.Vec(IDL.Text),
    'totalPurchaseValue' : IDL.Float64,
    'transactions' : IDL.Vec(Transaction),
    'unrealizedProfitLoss' : IDL.Float64,
  });
  const AuthResult = IDL.Variant({
    'ok' : IDL.Vec(Portfolio),
    'notFound' : IDL.Text,
    'unauthorized' : IDL.Text,
  });
  const PriorityAsset = IDL.Record({
    'id' : IDL.Text,
    'marketCap' : IDL.Float64,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const TechnicalData = IDL.Record({
    'currentPrice' : IDL.Float64,
    'change24h' : IDL.Float64,
    'marketCap' : IDL.Float64,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'volume24h' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addCustomPriorityAsset' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Record({ 'error' : IDL.Opt(IDL.Text), 'success' : IDL.Bool })],
        [],
      ),
    'addTransaction' : IDL.Func([IDL.Nat, Transaction], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPortfolio' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deletePortfolio' : IDL.Func([IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'editTransaction' : IDL.Func([IDL.Nat, IDL.Nat, Transaction], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'fetchHistoricalPriceData' : IDL.Func([IDL.Text], [IDL.Text], []),
    'fetchMarketData' : IDL.Func([], [], []),
    'fetchPriorityAssetPrices' : IDL.Func([], [], []),
    'fetchTechnicalData' : IDL.Func([IDL.Text], [], []),
    'getAvailableAssets' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserProfileWithStatus' : IDL.Func([], [AuthResult_1], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomPriorityAssets' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getHistoricalPrice' : IDL.Func([IDL.Text, IDL.Int], [IDL.Float64], []),
    'getLastFetchError' : IDL.Func(
        [],
        [
          IDL.Record({
            'marketData' : IDL.Opt(
              IDL.Record({ 'error' : IDL.Text, 'timestamp' : IDL.Int })
            ),
            'priorityAssets' : IDL.Opt(
              IDL.Record({ 'error' : IDL.Text, 'timestamp' : IDL.Int })
            ),
            'technicalData' : IDL.Opt(
              IDL.Record({ 'error' : IDL.Text, 'timestamp' : IDL.Int })
            ),
          }),
        ],
        ['query'],
      ),
    'getMarketData' : IDL.Func([], [IDL.Vec(MarketData)], ['query']),
    'getMarketDataStatus' : IDL.Func(
        [],
        [IDL.Opt(MarketDataStatus)],
        ['query'],
      ),
    'getPortfolioAssets' : IDL.Func([IDL.Nat], [IDL.Vec(Asset)], ['query']),
    'getPortfolioSummary' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Opt(
            IDL.Record({
              'totalProfitLoss' : IDL.Float64,
              'totalValue' : IDL.Float64,
              'totalPurchaseValue' : IDL.Float64,
              'unrealizedProfitLoss' : IDL.Float64,
            })
          ),
        ],
        ['query'],
      ),
    'getPortfolioTrackedAssets' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getPortfolioTransactions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getPortfolios' : IDL.Func([], [IDL.Vec(Portfolio)], ['query']),
    'getPortfoliosWithStatus' : IDL.Func([], [AuthResult], ['query']),
    'getPriorityAssets' : IDL.Func([], [IDL.Vec(PriorityAsset)], ['query']),
    'getSystemHealth' : IDL.Func(
        [],
        [
          IDL.Record({
            'isHealthy' : IDL.Bool,
            'currentTime' : IDL.Int,
            'lastCheck' : IDL.Int,
          }),
        ],
        ['query'],
      ),
    'getTechnicalData' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TechnicalData)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isAuthenticated' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeCustomPriorityAsset' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'error' : IDL.Opt(IDL.Text), 'success' : IDL.Bool })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchCoinGeckoTokens' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'results' : IDL.Vec(
              IDL.Record({
                'id' : IDL.Text,
                'name' : IDL.Text,
                'symbol' : IDL.Text,
              })
            ),
            'error' : IDL.Opt(IDL.Text),
          }),
        ],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAssetPrices' : IDL.Func([IDL.Nat], [], []),
    'updateMarketDataStatus' : IDL.Func([MarketDataStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };