/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Asset {
  'currentPrice' : number,
  'averagePrice' : number,
  'realizedProfitLossPercentage' : number,
  'name' : string,
  'averagePurchasePrice' : number,
  'profitLoss' : number,
  'currentValue' : number,
  'purchaseValue' : number,
  'profitLossPercentage' : number,
  'amount' : number,
  'totalSoldCost' : number,
  'realizedProfitLoss' : number,
  'symbol' : string,
}
export type AuthResult = { 'ok' : Array<Portfolio> } |
  { 'notFound' : string } |
  { 'unauthorized' : string };
export type AuthResult_1 = { 'ok' : UserProfile } |
  { 'notFound' : string } |
  { 'unauthorized' : string };
export interface Cell { 'value' : Value, 'name' : string }
export interface ExchangeRate {
  'rate' : number,
  'lastUpdated' : bigint,
  'sourceTimestamp' : bigint,
  'lastError' : [] | [string],
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface MarketData {
  'id' : bigint,
  'marketCap' : number,
  'name' : string,
  'lastUpdated' : bigint,
  'price' : number,
  'symbol' : string,
}
export interface MarketDataStatus {
  'status' : string,
  'calculationQuality' : number,
  'apiHealth' : string,
  'lastUpdated' : bigint,
  'trackedAssetsCount' : bigint,
  'colorScheme' : string,
}
export interface Portfolio {
  'id' : bigint,
  'totalProfitLoss' : number,
  'totalValue' : number,
  'name' : string,
  'createdAt' : bigint,
  'assets' : Array<Asset>,
  'trackedAssets' : Array<string>,
  'totalPurchaseValue' : number,
  'transactions' : Array<Transaction>,
  'unrealizedProfitLoss' : number,
}
export interface PriorityAsset {
  'id' : string,
  'marketCap' : number,
  'name' : string,
  'lastUpdated' : bigint,
  'price' : number,
  'symbol' : string,
}
export interface RefreshResult {
  'marketDataError' : [] | [string],
  'priorityAssetsOk' : boolean,
  'marketDataOk' : boolean,
  'priorityAssetsError' : [] | [string],
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface TechnicalData {
  'currentPrice' : number,
  'change24h' : number,
  'marketCap' : number,
  'name' : string,
  'lastUpdated' : bigint,
  'volume24h' : number,
  'symbol' : string,
}
export interface Transaction {
  'id' : bigint,
  'date' : bigint,
  'type' : string,
  'comment' : string,
  'assetSymbol' : string,
  'assetName' : string,
  'price' : number,
  'amount' : number,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface UserProfile {
  'theme' : string,
  'name' : string,
  'language' : string,
  'colorScheme' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addCustomPriorityAsset' : ActorMethod<
    [string, string],
    { 'error' : [] | [string], 'success' : boolean }
  >,
  'addTransaction' : ActorMethod<[bigint, Transaction], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPortfolio' : ActorMethod<[string], bigint>,
  'deletePortfolio' : ActorMethod<[bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint, bigint], undefined>,
  'editTransaction' : ActorMethod<[bigint, bigint, Transaction], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'fetchHistoricalPriceData' : ActorMethod<[string], string>,
  'fetchMarketData' : ActorMethod<[], undefined>,
  'fetchPriorityAssetPrices' : ActorMethod<[], undefined>,
  'fetchTechnicalData' : ActorMethod<[string], undefined>,
  'getApiDoc' : ActorMethod<[], string>,
  'getAvailableAssets' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserProfileWithStatus' : ActorMethod<[], AuthResult_1>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomPriorityAssets' : ActorMethod<[], Array<[string, string]>>,
  'getExchangeRate' : ActorMethod<[], [] | [ExchangeRate]>,
  'getHistoricalPrice' : ActorMethod<[string, bigint], number>,
  'getLastFetchError' : ActorMethod<
    [],
    {
      'marketData' : [] | [{ 'error' : string, 'timestamp' : bigint }],
      'priorityAssets' : [] | [{ 'error' : string, 'timestamp' : bigint }],
      'technicalData' : [] | [{ 'error' : string, 'timestamp' : bigint }],
    }
  >,
  'getMarketData' : ActorMethod<[], Array<MarketData>>,
  'getMarketDataStatus' : ActorMethod<[], [] | [MarketDataStatus]>,
  'getPortfolioAssets' : ActorMethod<[bigint], Array<Asset>>,
  'getPortfolioSummary' : ActorMethod<
    [bigint],
    [] | [
      {
        'totalProfitLoss' : number,
        'totalValue' : number,
        'totalPurchaseValue' : number,
        'unrealizedProfitLoss' : number,
      }
    ]
  >,
  'getPortfolioTrackedAssets' : ActorMethod<[bigint], Array<string>>,
  'getPortfolioTransactions' : ActorMethod<[bigint], Array<Transaction>>,
  'getPortfolios' : ActorMethod<[], Array<Portfolio>>,
  'getPortfoliosWithStatus' : ActorMethod<[], AuthResult>,
  'getPriorityAssets' : ActorMethod<[], Array<PriorityAsset>>,
  'getSystemHealth' : ActorMethod<
    [],
    { 'isHealthy' : boolean, 'currentTime' : bigint, 'lastCheck' : bigint }
  >,
  'getTechnicalData' : ActorMethod<[string], [] | [TechnicalData]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isAuthenticated' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'refreshAllPrices' : ActorMethod<[], RefreshResult>,
  'refreshExchangeRate' : ActorMethod<[], ExchangeRate>,
  'removeCustomPriorityAsset' : ActorMethod<
    [string],
    { 'error' : [] | [string], 'success' : boolean }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'schema' : ActorMethod<[], string>,
  'searchCoinGeckoTokens' : ActorMethod<
    [string],
    {
      'results' : Array<{ 'id' : string, 'name' : string, 'symbol' : string }>,
      'error' : [] | [string],
    }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAssetPrices' : ActorMethod<[bigint], undefined>,
  'updateMarketDataStatus' : ActorMethod<[MarketDataStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];