/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Asset {
  'currentPrice' : number,
  'averagePrice' : number,
  'name' : string,
  'averagePurchasePrice' : number,
  'profitLoss' : number,
  'currentValue' : number,
  'purchaseValue' : number,
  'profitLossPercentage' : number,
  'amount' : number,
  'realizedProfitLoss' : number,
  'symbol' : string,
}
export type AuthResult = { 'ok' : Array<Portfolio> } |
  { 'notFound' : string } |
  { 'unauthorized' : string };
export type AuthResult_1 = { 'ok' : UserProfile } |
  { 'notFound' : string } |
  { 'unauthorized' : string };
export interface HistoricalProfitLoss {
  'totalProfitLoss' : number,
  'timestamp' : bigint,
}
export interface HistoricalTotalValue {
  'totalValue' : number,
  'timestamp' : bigint,
}
export interface HistoricalUnrealizedProfitLoss {
  'timestamp' : bigint,
  'unrealizedProfitLoss' : number,
}
export interface HistoricalValue { 'totalValue' : number, 'timestamp' : bigint }
export interface MarketData {
  'id' : bigint,
  'marketCap' : number,
  'name' : string,
  'lastUpdated' : bigint,
  'price' : number,
  'symbol' : string,
}
export interface MarketDataStatus {
  'status' : string,
  'calculationQuality' : number,
  'apiHealth' : string,
  'lastUpdated' : bigint,
  'trackedAssetsCount' : bigint,
  'colorScheme' : string,
}
export interface Portfolio {
  'id' : bigint,
  'historicalUnrealizedProfitLoss' : Array<HistoricalUnrealizedProfitLoss>,
  'historicalValues' : Array<HistoricalValue>,
  'totalProfitLoss' : number,
  'historicalTotalValue' : Array<HistoricalTotalValue>,
  'name' : string,
  'createdAt' : bigint,
  'assets' : Array<Asset>,
  'historicalProfitLoss' : Array<HistoricalProfitLoss>,
  'trackedAssets' : Array<string>,
  'totalPurchaseValue' : number,
  'transactions' : Array<Transaction>,
  'unrealizedProfitLoss' : number,
}
export interface PriorityAsset {
  'id' : string,
  'marketCap' : number,
  'name' : string,
  'lastUpdated' : bigint,
  'price' : number,
  'symbol' : string,
}
export interface TechnicalData {
  'currentPrice' : number,
  'change24h' : number,
  'marketCap' : number,
  'name' : string,
  'lastUpdated' : bigint,
  'volume24h' : number,
  'symbol' : string,
}
export interface Transaction {
  'id' : bigint,
  'date' : bigint,
  'type' : string,
  'comment' : string,
  'assetSymbol' : string,
  'assetName' : string,
  'price' : number,
  'amount' : number,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'theme' : string,
  'name' : string,
  'language' : string,
  'colorScheme' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addTransaction' : ActorMethod<[bigint, Transaction], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPortfolio' : ActorMethod<[string], bigint>,
  'deletePortfolio' : ActorMethod<[bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint, bigint], undefined>,
  'editTransaction' : ActorMethod<[bigint, bigint, Transaction], undefined>,
  'fetchHistoricalPriceData' : ActorMethod<[string], string>,
  'fetchMarketData' : ActorMethod<[], undefined>,
  'fetchPriorityAssetPrices' : ActorMethod<[], undefined>,
  'fetchTechnicalData' : ActorMethod<[string], undefined>,
  'getAvailableAssets' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserProfileWithStatus' : ActorMethod<[], AuthResult_1>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMarketData' : ActorMethod<[], Array<MarketData>>,
  'getMarketDataStatus' : ActorMethod<[], [] | [MarketDataStatus]>,
  'getPortfolioAssets' : ActorMethod<[bigint], Array<Asset>>,
  'getPortfolioHistoricalProfitLoss' : ActorMethod<
    [bigint],
    Array<HistoricalProfitLoss>
  >,
  'getPortfolioHistoricalTotalValue' : ActorMethod<
    [bigint],
    Array<HistoricalTotalValue>
  >,
  'getPortfolioHistoricalUnrealizedProfitLoss' : ActorMethod<
    [bigint],
    Array<HistoricalUnrealizedProfitLoss>
  >,
  'getPortfolioHistoricalValues' : ActorMethod<
    [bigint],
    Array<HistoricalValue>
  >,
  'getPortfolioSummary' : ActorMethod<
    [bigint],
    [] | [
      {
        'totalProfitLoss' : number,
        'totalValue' : number,
        'totalPurchaseValue' : number,
        'unrealizedProfitLoss' : number,
      }
    ]
  >,
  'getPortfolioTrackedAssets' : ActorMethod<[bigint], Array<string>>,
  'getPortfolioTransactions' : ActorMethod<[bigint], Array<Transaction>>,
  'getPortfolios' : ActorMethod<[], Array<Portfolio>>,
  'getPortfoliosWithStatus' : ActorMethod<[], AuthResult>,
  'getPriorityAssets' : ActorMethod<[], Array<PriorityAsset>>,
  'getSystemHealth' : ActorMethod<
    [],
    { 'isHealthy' : boolean, 'currentTime' : bigint, 'lastCheck' : bigint }
  >,
  'getTechnicalData' : ActorMethod<[string], [] | [TechnicalData]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isAuthenticated' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAssetPrices' : ActorMethod<[bigint], undefined>,
  'updateMarketDataStatus' : ActorMethod<[MarketDataStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];