/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface HistoricalValue {
    totalValue: number;
    timestamp: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface HttpRequestResult {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface MarketDataStatus {
    status: string;
    calculationQuality: number;
    apiHealth: string;
    lastUpdated: bigint;
    trackedAssetsCount: bigint;
    colorScheme: string;
}
export type AuthResult_1 = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "notFound";
    notFound: string;
} | {
    __kind__: "unauthorized";
    unauthorized: string;
};
export interface HttpHeader {
    value: string;
    name: string;
}
export interface MarketData {
    id: bigint;
    marketCap: number;
    name: string;
    lastUpdated: bigint;
    price: number;
    symbol: string;
}
export interface Transaction {
    id: bigint;
    date: bigint;
    type: string;
    comment: string;
    assetSymbol: string;
    assetName: string;
    price: number;
    amount: number;
}
export interface TechnicalData {
    currentPrice: number;
    change24h: number;
    marketCap: number;
    name: string;
    lastUpdated: bigint;
    volume24h: number;
    symbol: string;
}
export interface HistoricalTotalValue {
    totalValue: number;
    timestamp: bigint;
}
export interface HistoricalProfitLoss {
    totalProfitLoss: number;
    timestamp: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: HttpRequestResult;
}
export interface Asset {
    currentPrice: number;
    averagePrice: number;
    realizedProfitLossPercentage: number;
    name: string;
    averagePurchasePrice: number;
    profitLoss: number;
    currentValue: number;
    purchaseValue: number;
    profitLossPercentage: number;
    amount: number;
    totalSoldCost: number;
    realizedProfitLoss: number;
    symbol: string;
}
export interface Portfolio {
    id: bigint;
    historicalUnrealizedProfitLoss: Array<HistoricalUnrealizedProfitLoss>;
    historicalValues: Array<HistoricalValue>;
    totalProfitLoss: number;
    historicalTotalValue: Array<HistoricalTotalValue>;
    name: string;
    createdAt: bigint;
    assets: Array<Asset>;
    historicalProfitLoss: Array<HistoricalProfitLoss>;
    trackedAssets: Array<string>;
    totalPurchaseValue: number;
    transactions: Array<Transaction>;
    unrealizedProfitLoss: number;
}
export interface PriorityAsset {
    id: string;
    marketCap: number;
    name: string;
    lastUpdated: bigint;
    price: number;
    symbol: string;
}
export interface HistoricalUnrealizedProfitLoss {
    timestamp: bigint;
    unrealizedProfitLoss: number;
}
export type AuthResult = {
    __kind__: "ok";
    ok: Array<Portfolio>;
} | {
    __kind__: "notFound";
    notFound: string;
} | {
    __kind__: "unauthorized";
    unauthorized: string;
};
export interface UserProfile {
    theme: string;
    name: string;
    language: string;
    colorScheme: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addTransaction(portfolioId: bigint, transaction: Transaction): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPortfolio(name: string): Promise<bigint>;
    deletePortfolio(portfolioId: bigint): Promise<void>;
    deleteTransaction(portfolioId: bigint, transactionId: bigint): Promise<void>;
    editTransaction(portfolioId: bigint, transactionId: bigint, updatedTransaction: Transaction): Promise<void>;
    fetchHistoricalPriceData(assetId: string): Promise<string>;
    fetchMarketData(): Promise<void>;
    fetchPriorityAssetPrices(): Promise<void>;
    fetchTechnicalData(assetId: string): Promise<void>;
    getAvailableAssets(): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserProfileWithStatus(): Promise<AuthResult_1>;
    getCallerUserRole(): Promise<UserRole>;
    getLastFetchError(): Promise<{
        marketData?: {
            error: string;
            timestamp: bigint;
        };
        priorityAssets?: {
            error: string;
            timestamp: bigint;
        };
        technicalData?: {
            error: string;
            timestamp: bigint;
        };
    }>;
    getMarketData(): Promise<Array<MarketData>>;
    getMarketDataStatus(): Promise<MarketDataStatus | null>;
    getPortfolioAssets(portfolioId: bigint): Promise<Array<Asset>>;
    getPortfolioHistoricalProfitLoss(portfolioId: bigint): Promise<Array<HistoricalProfitLoss>>;
    getPortfolioHistoricalTotalValue(portfolioId: bigint): Promise<Array<HistoricalTotalValue>>;
    getPortfolioHistoricalUnrealizedProfitLoss(portfolioId: bigint): Promise<Array<HistoricalUnrealizedProfitLoss>>;
    getPortfolioHistoricalValues(portfolioId: bigint): Promise<Array<HistoricalValue>>;
    getPortfolioSummary(portfolioId: bigint): Promise<{
        totalProfitLoss: number;
        totalValue: number;
        totalPurchaseValue: number;
        unrealizedProfitLoss: number;
    } | null>;
    getPortfolioTrackedAssets(portfolioId: bigint): Promise<Array<string>>;
    getPortfolioTransactions(portfolioId: bigint): Promise<Array<Transaction>>;
    getPortfolios(): Promise<Array<Portfolio>>;
    getPortfoliosWithStatus(): Promise<AuthResult>;
    getPriorityAssets(): Promise<Array<PriorityAsset>>;
    getSystemHealth(): Promise<{
        isHealthy: boolean;
        currentTime: bigint;
        lastCheck: bigint;
    }>;
    getTechnicalData(assetId: string): Promise<TechnicalData | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isAuthenticated(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAssetPrices(portfolioId: bigint): Promise<void>;
    updateMarketDataStatus(status: MarketDataStatus): Promise<void>;
}
import type { AuthResult as _AuthResult, AuthResult_1 as _AuthResult_1, MarketDataStatus as _MarketDataStatus, Portfolio as _Portfolio, TechnicalData as _TechnicalData, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addTransaction(arg0: bigint, arg1: Transaction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPortfolio(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPortfolio(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPortfolio(arg0);
            return result;
        }
    }
    async deletePortfolio(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePortfolio(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePortfolio(arg0);
            return result;
        }
    }
    async deleteTransaction(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0, arg1);
            return result;
        }
    }
    async editTransaction(arg0: bigint, arg1: bigint, arg2: Transaction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editTransaction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editTransaction(arg0, arg1, arg2);
            return result;
        }
    }
    async fetchHistoricalPriceData(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchHistoricalPriceData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchHistoricalPriceData(arg0);
            return result;
        }
    }
    async fetchMarketData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchMarketData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchMarketData();
            return result;
        }
    }
    async fetchPriorityAssetPrices(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchPriorityAssetPrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchPriorityAssetPrices();
            return result;
        }
    }
    async fetchTechnicalData(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchTechnicalData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchTechnicalData(arg0);
            return result;
        }
    }
    async getAvailableAssets(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableAssets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableAssets();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfileWithStatus(): Promise<AuthResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfileWithStatus();
                return from_candid_AuthResult_1_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfileWithStatus();
            return from_candid_AuthResult_1_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLastFetchError(): Promise<{
        marketData?: {
            error: string;
            timestamp: bigint;
        };
        priorityAssets?: {
            error: string;
            timestamp: bigint;
        };
        technicalData?: {
            error: string;
            timestamp: bigint;
        };
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastFetchError();
                return from_candid_record_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastFetchError();
            return from_candid_record_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketData(): Promise<Array<MarketData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketData();
            return result;
        }
    }
    async getMarketDataStatus(): Promise<MarketDataStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketDataStatus();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketDataStatus();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioAssets(arg0: bigint): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioAssets(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioAssets(arg0);
            return result;
        }
    }
    async getPortfolioHistoricalProfitLoss(arg0: bigint): Promise<Array<HistoricalProfitLoss>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioHistoricalProfitLoss(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioHistoricalProfitLoss(arg0);
            return result;
        }
    }
    async getPortfolioHistoricalTotalValue(arg0: bigint): Promise<Array<HistoricalTotalValue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioHistoricalTotalValue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioHistoricalTotalValue(arg0);
            return result;
        }
    }
    async getPortfolioHistoricalUnrealizedProfitLoss(arg0: bigint): Promise<Array<HistoricalUnrealizedProfitLoss>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioHistoricalUnrealizedProfitLoss(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioHistoricalUnrealizedProfitLoss(arg0);
            return result;
        }
    }
    async getPortfolioHistoricalValues(arg0: bigint): Promise<Array<HistoricalValue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioHistoricalValues(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioHistoricalValues(arg0);
            return result;
        }
    }
    async getPortfolioSummary(arg0: bigint): Promise<{
        totalProfitLoss: number;
        totalValue: number;
        totalPurchaseValue: number;
        unrealizedProfitLoss: number;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioSummary(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioSummary(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioTrackedAssets(arg0: bigint): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioTrackedAssets(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioTrackedAssets(arg0);
            return result;
        }
    }
    async getPortfolioTransactions(arg0: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioTransactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioTransactions(arg0);
            return result;
        }
    }
    async getPortfolios(): Promise<Array<Portfolio>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolios();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolios();
            return result;
        }
    }
    async getPortfoliosWithStatus(): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfoliosWithStatus();
                return from_candid_AuthResult_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfoliosWithStatus();
            return from_candid_AuthResult_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPriorityAssets(): Promise<Array<PriorityAsset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPriorityAssets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPriorityAssets();
            return result;
        }
    }
    async getSystemHealth(): Promise<{
        isHealthy: boolean;
        currentTime: bigint;
        lastCheck: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemHealth();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemHealth();
            return result;
        }
    }
    async getTechnicalData(arg0: string): Promise<TechnicalData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTechnicalData(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTechnicalData(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isAuthenticated(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAuthenticated();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAuthenticated();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAssetPrices(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssetPrices(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssetPrices(arg0);
            return result;
        }
    }
    async updateMarketDataStatus(arg0: MarketDataStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMarketDataStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMarketDataStatus(arg0);
            return result;
        }
    }
}
function from_candid_AuthResult_1_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResult_1): AuthResult_1 {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_AuthResult_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResult): AuthResult {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MarketDataStatus]): MarketDataStatus | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        totalProfitLoss: number;
        totalValue: number;
        totalPurchaseValue: number;
        unrealizedProfitLoss: number;
    }]): {
    totalProfitLoss: number;
    totalValue: number;
    totalPurchaseValue: number;
    unrealizedProfitLoss: number;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TechnicalData]): TechnicalData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        error: string;
        timestamp: bigint;
    }]): {
    error: string;
    timestamp: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marketData: [] | [{
            error: string;
            timestamp: bigint;
        }];
    priorityAssets: [] | [{
            error: string;
            timestamp: bigint;
        }];
    technicalData: [] | [{
            error: string;
            timestamp: bigint;
        }];
}): {
    marketData?: {
        error: string;
        timestamp: bigint;
    };
    priorityAssets?: {
        error: string;
        timestamp: bigint;
    };
    technicalData?: {
        error: string;
        timestamp: bigint;
    };
} {
    return {
        marketData: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.marketData)),
        priorityAssets: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.priorityAssets)),
        technicalData: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.technicalData))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Portfolio>;
} | {
    notFound: string;
} | {
    unauthorized: string;
}): {
    __kind__: "ok";
    ok: Array<Portfolio>;
} | {
    __kind__: "notFound";
    notFound: string;
} | {
    __kind__: "unauthorized";
    unauthorized: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    notFound: string;
} | {
    unauthorized: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "notFound";
    notFound: string;
} | {
    __kind__: "unauthorized";
    unauthorized: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
