/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Asset {
    currentPrice: number;
    averagePrice: number;
    realizedProfitLossPercentage: number;
    name: string;
    averagePurchasePrice: number;
    profitLoss: number;
    currentValue: number;
    purchaseValue: number;
    profitLossPercentage: number;
    amount: number;
    totalSoldCost: number;
    realizedProfitLoss: number;
    symbol: string;
}
export type AuthResult = {
    __kind__: "ok";
    ok: Array<Portfolio>;
} | {
    __kind__: "notFound";
    notFound: string;
} | {
    __kind__: "unauthorized";
    unauthorized: string;
};
export type AuthResult_1 = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "notFound";
    notFound: string;
} | {
    __kind__: "unauthorized";
    unauthorized: string;
};
export interface Cell {
    value: Value;
    name: string;
}
export interface ExchangeRate {
    rate: number;
    lastUpdated: bigint;
    sourceTimestamp: bigint;
    lastError?: string;
}
export interface HttpHeader {
    value: string;
    name: string;
}
export interface HttpRequestResult {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface MarketData {
    id: bigint;
    marketCap: number;
    name: string;
    lastUpdated: bigint;
    price: number;
    symbol: string;
}
export interface MarketDataStatus {
    status: string;
    calculationQuality: number;
    apiHealth: string;
    lastUpdated: bigint;
    trackedAssetsCount: bigint;
    colorScheme: string;
}
export interface Portfolio {
    id: bigint;
    totalProfitLoss: number;
    totalValue: number;
    name: string;
    createdAt: bigint;
    assets: Array<Asset>;
    trackedAssets: Array<string>;
    totalPurchaseValue: number;
    transactions: Array<Transaction>;
    unrealizedProfitLoss: number;
}
export interface PriorityAsset {
    id: string;
    marketCap: number;
    name: string;
    lastUpdated: bigint;
    price: number;
    symbol: string;
}
export interface RefreshResult {
    marketDataError?: string;
    priorityAssetsOk: boolean;
    marketDataOk: boolean;
    priorityAssetsError?: string;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface TechnicalData {
    currentPrice: number;
    change24h: number;
    marketCap: number;
    name: string;
    lastUpdated: bigint;
    volume24h: number;
    symbol: string;
}
export interface Transaction {
    id: bigint;
    date: bigint;
    type: string;
    comment: string;
    assetSymbol: string;
    assetName: string;
    price: number;
    amount: number;
}
export interface TransformationInput {
    context: Uint8Array;
    response: HttpRequestResult;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface UserProfile {
    theme: string;
    name: string;
    language: string;
    colorScheme: string;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addCustomPriorityAsset(coinGeckoId: string, tickerSymbol: string): Promise<{
        error?: string;
        success: boolean;
    }>;
    addTransaction(portfolioId: bigint, transaction: Transaction): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPortfolio(name: string): Promise<bigint>;
    deletePortfolio(portfolioId: bigint): Promise<void>;
    deleteTransaction(portfolioId: bigint, transactionId: bigint): Promise<void>;
    editTransaction(portfolioId: bigint, transactionId: bigint, updatedTransaction: Transaction): Promise<void>;
    execute(qJson: string): Promise<Result>;
    fetchHistoricalPriceData(assetId: string): Promise<string>;
    fetchMarketData(): Promise<void>;
    fetchPriorityAssetPrices(): Promise<void>;
    fetchTechnicalData(assetId: string): Promise<void>;
    getApiDoc(): Promise<string>;
    getAvailableAssets(): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserProfileWithStatus(): Promise<AuthResult_1>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomPriorityAssets(): Promise<Array<[string, string]>>;
    getExchangeRate(): Promise<ExchangeRate | null>;
    getHistoricalPrice(coinGeckoId: string, date: bigint): Promise<number>;
    getLastFetchError(): Promise<{
        marketData?: {
            error: string;
            timestamp: bigint;
        };
        priorityAssets?: {
            error: string;
            timestamp: bigint;
        };
        technicalData?: {
            error: string;
            timestamp: bigint;
        };
    }>;
    getMarketData(): Promise<Array<MarketData>>;
    getMarketDataStatus(): Promise<MarketDataStatus | null>;
    getPortfolioAssets(portfolioId: bigint): Promise<Array<Asset>>;
    getPortfolioSummary(portfolioId: bigint): Promise<{
        totalProfitLoss: number;
        totalValue: number;
        totalPurchaseValue: number;
        unrealizedProfitLoss: number;
    } | null>;
    getPortfolioTrackedAssets(portfolioId: bigint): Promise<Array<string>>;
    getPortfolioTransactions(portfolioId: bigint): Promise<Array<Transaction>>;
    getPortfolios(): Promise<Array<Portfolio>>;
    getPortfoliosWithStatus(): Promise<AuthResult>;
    getPriorityAssets(): Promise<Array<PriorityAsset>>;
    getSystemHealth(): Promise<{
        isHealthy: boolean;
        currentTime: bigint;
        lastCheck: bigint;
    }>;
    getTechnicalData(assetId: string): Promise<TechnicalData | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isAuthenticated(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    refreshAllPrices(): Promise<RefreshResult>;
    refreshExchangeRate(): Promise<ExchangeRate>;
    removeCustomPriorityAsset(coinGeckoId: string): Promise<{
        error?: string;
        success: boolean;
    }>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    schema(): Promise<string>;
    searchCoinGeckoTokens(searchQuery: string): Promise<{
        results: Array<{
            id: string;
            name: string;
            symbol: string;
        }>;
        error?: string;
    }>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAssetPrices(portfolioId: bigint): Promise<void>;
    updateMarketDataStatus(status: MarketDataStatus): Promise<void>;
}
import type { AuthResult as _AuthResult, AuthResult_1 as _AuthResult_1, Cell as _Cell, ExchangeRate as _ExchangeRate, MarketDataStatus as _MarketDataStatus, Portfolio as _Portfolio, RefreshResult as _RefreshResult, Result as _Result, TechnicalData as _TechnicalData, UserProfile as _UserProfile, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addCustomPriorityAsset(arg0: string, arg1: string): Promise<{
        error?: string;
        success: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomPriorityAsset(arg0, arg1);
                return from_candid_record_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomPriorityAsset(arg0, arg1);
            return from_candid_record_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addTransaction(arg0: bigint, arg1: Transaction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPortfolio(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPortfolio(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPortfolio(arg0);
            return result;
        }
    }
    async deletePortfolio(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePortfolio(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePortfolio(arg0);
            return result;
        }
    }
    async deleteTransaction(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0, arg1);
            return result;
        }
    }
    async editTransaction(arg0: bigint, arg1: bigint, arg2: Transaction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editTransaction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editTransaction(arg0, arg1, arg2);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchHistoricalPriceData(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchHistoricalPriceData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchHistoricalPriceData(arg0);
            return result;
        }
    }
    async fetchMarketData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchMarketData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchMarketData();
            return result;
        }
    }
    async fetchPriorityAssetPrices(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchPriorityAssetPrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchPriorityAssetPrices();
            return result;
        }
    }
    async fetchTechnicalData(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchTechnicalData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchTechnicalData(arg0);
            return result;
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getAvailableAssets(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableAssets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableAssets();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfileWithStatus(): Promise<AuthResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfileWithStatus();
                return from_candid_AuthResult_1_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfileWithStatus();
            return from_candid_AuthResult_1_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomPriorityAssets(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomPriorityAssets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomPriorityAssets();
            return result;
        }
    }
    async getExchangeRate(): Promise<ExchangeRate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExchangeRate();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExchangeRate();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHistoricalPrice(arg0: string, arg1: bigint): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistoricalPrice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistoricalPrice(arg0, arg1);
            return result;
        }
    }
    async getLastFetchError(): Promise<{
        marketData?: {
            error: string;
            timestamp: bigint;
        };
        priorityAssets?: {
            error: string;
            timestamp: bigint;
        };
        technicalData?: {
            error: string;
            timestamp: bigint;
        };
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastFetchError();
                return from_candid_record_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastFetchError();
            return from_candid_record_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketData(): Promise<Array<MarketData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketData();
            return result;
        }
    }
    async getMarketDataStatus(): Promise<MarketDataStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketDataStatus();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketDataStatus();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioAssets(arg0: bigint): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioAssets(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioAssets(arg0);
            return result;
        }
    }
    async getPortfolioSummary(arg0: bigint): Promise<{
        totalProfitLoss: number;
        totalValue: number;
        totalPurchaseValue: number;
        unrealizedProfitLoss: number;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioSummary(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioSummary(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioTrackedAssets(arg0: bigint): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioTrackedAssets(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioTrackedAssets(arg0);
            return result;
        }
    }
    async getPortfolioTransactions(arg0: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioTransactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioTransactions(arg0);
            return result;
        }
    }
    async getPortfolios(): Promise<Array<Portfolio>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolios();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolios();
            return result;
        }
    }
    async getPortfoliosWithStatus(): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfoliosWithStatus();
                return from_candid_AuthResult_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfoliosWithStatus();
            return from_candid_AuthResult_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPriorityAssets(): Promise<Array<PriorityAsset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPriorityAssets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPriorityAssets();
            return result;
        }
    }
    async getSystemHealth(): Promise<{
        isHealthy: boolean;
        currentTime: bigint;
        lastCheck: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemHealth();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemHealth();
            return result;
        }
    }
    async getTechnicalData(arg0: string): Promise<TechnicalData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTechnicalData(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTechnicalData(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isAuthenticated(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAuthenticated();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAuthenticated();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async refreshAllPrices(): Promise<RefreshResult> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshAllPrices();
                return from_candid_RefreshResult_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshAllPrices();
            return from_candid_RefreshResult_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async refreshExchangeRate(): Promise<ExchangeRate> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshExchangeRate();
                return from_candid_ExchangeRate_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshExchangeRate();
            return from_candid_ExchangeRate_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeCustomPriorityAsset(arg0: string): Promise<{
        error?: string;
        success: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCustomPriorityAsset(arg0);
                return from_candid_record_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCustomPriorityAsset(arg0);
            return from_candid_record_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async searchCoinGeckoTokens(arg0: string): Promise<{
        results: Array<{
            id: string;
            name: string;
            symbol: string;
        }>;
        error?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCoinGeckoTokens(arg0);
                return from_candid_record_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCoinGeckoTokens(arg0);
            return from_candid_record_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAssetPrices(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssetPrices(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssetPrices(arg0);
            return result;
        }
    }
    async updateMarketDataStatus(arg0: MarketDataStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMarketDataStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMarketDataStatus(arg0);
            return result;
        }
    }
}
function from_candid_AuthResult_1_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResult_1): AuthResult_1 {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_AuthResult_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResult): AuthResult {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ExchangeRate_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExchangeRate): ExchangeRate {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_RefreshResult_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RefreshResult): RefreshResult {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExchangeRate]): ExchangeRate | null {
    return value.length === 0 ? null : from_candid_ExchangeRate_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        error: string;
        timestamp: bigint;
    }]): {
    error: string;
    timestamp: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MarketDataStatus]): MarketDataStatus | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        totalProfitLoss: number;
        totalValue: number;
        totalPurchaseValue: number;
        unrealizedProfitLoss: number;
    }]): {
    totalProfitLoss: number;
    totalValue: number;
    totalPurchaseValue: number;
    unrealizedProfitLoss: number;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TechnicalData]): TechnicalData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: [] | [string];
    success: boolean;
}): {
    error?: string;
    success: boolean;
} {
    return {
        error: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.error)),
        success: value.success
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rate: number;
    lastUpdated: bigint;
    sourceTimestamp: bigint;
    lastError: [] | [string];
}): {
    rate: number;
    lastUpdated: bigint;
    sourceTimestamp: bigint;
    lastError?: string;
} {
    return {
        rate: value.rate,
        lastUpdated: value.lastUpdated,
        sourceTimestamp: value.sourceTimestamp,
        lastError: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.lastError))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marketData: [] | [{
            error: string;
            timestamp: bigint;
        }];
    priorityAssets: [] | [{
            error: string;
            timestamp: bigint;
        }];
    technicalData: [] | [{
            error: string;
            timestamp: bigint;
        }];
}): {
    marketData?: {
        error: string;
        timestamp: bigint;
    };
    priorityAssets?: {
        error: string;
        timestamp: bigint;
    };
    technicalData?: {
        error: string;
        timestamp: bigint;
    };
} {
    return {
        marketData: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.marketData)),
        priorityAssets: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.priorityAssets)),
        technicalData: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.technicalData))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marketDataError: [] | [string];
    priorityAssetsOk: boolean;
    marketDataOk: boolean;
    priorityAssetsError: [] | [string];
}): {
    marketDataError?: string;
    priorityAssetsOk: boolean;
    marketDataOk: boolean;
    priorityAssetsError?: string;
} {
    return {
        marketDataError: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.marketDataError)),
        priorityAssetsOk: value.priorityAssetsOk,
        marketDataOk: value.marketDataOk,
        priorityAssetsError: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.priorityAssetsError))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    results: Array<{
        id: string;
        name: string;
        symbol: string;
    }>;
    error: [] | [string];
}): {
    results: Array<{
        id: string;
        name: string;
        symbol: string;
    }>;
    error?: string;
} {
    return {
        results: value.results,
        error: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.error))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n6(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n10(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    notFound: string;
} | {
    unauthorized: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "notFound";
    notFound: string;
} | {
    __kind__: "unauthorized";
    unauthorized: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Portfolio>;
} | {
    notFound: string;
} | {
    unauthorized: string;
}): {
    __kind__: "ok";
    ok: Array<Portfolio>;
} | {
    __kind__: "notFound";
    notFound: string;
} | {
    __kind__: "unauthorized";
    unauthorized: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n8(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
